services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=dispatchs'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'

  dispatchs:
    